fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_home:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /home

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

contact_list:
    path:      /list
    defaults:
        _controller: AppBundle:User:list

contact_add:
    path:      /add
    defaults:
        _controller: AppBundle:User:add

contact_delete:
    path:      /delete
    defaults:
        _controller: AppBundle:User:delete